### ISSUE TITLE
Can not link igraph library

### ISSUE THREAD

**Issue by keszocze** [msoeken/cirkit_addon_igraph#1]
When trying to build the addon, the linking process fails:

```
make[3]: *** No rule to make target '/libigraph.so', needed by 'programs/libcirkit_igraph.so'. Stop.
```
The problem is that you try to link against 
`${PC_LIBIGRAPH_LIBRARY_DIRS}/libigraph${CMAKE_SHARED_LIBRARY_SUFFIX}`. The variable `IMPORTED_TARGET` is empty on my system:
```
$ pkg-config --libs igraph
-ligraph
$ pkg-config --libs-only-L igraph

$
```

The following `CMakeLists.txt` lets me compile and link the addon:
```
find_package(PkgConfig)
pkg_check_modules(PC_LIBIGRAPH REQUIRED IMPORTED_TARGET igraph)

add_cirkit_library(
  NAME cirkit_igraph
  AUTO_DIRS src
  USE
    cirkit_classical
    cirkit_cli
    PkgConfig::PC_LIBIGRAPH
  INCLUDE
    PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src
    PUBLIC ${PC_LIBIGRAPH_INCLUDE_DIRS}
  DEFINE
    PUBLIC ADDON_IGRAPH
  COMMANDS
    classical/cli/commands/igraph_commands.hpp
)
```
My change is to use the `IMPORTED_TARGET` option that defines `PkgConfig::PC_LIBIGRAPH` as a valid target for cmake's `target_link_libraries()`.

I don't know whether this a general issue or somehow bound to my system. 
I am running Xubuntu 17.04, installed `libigraph0-dev` and `libigraph0v5` and use cmake version 3.7.2 and pkg-config version 0.29.1.

**Comment by msoeken** [comment]
This seems to be a legit fix. Would you mind creating a pull request, since you already modified the code? Thanks.

**Comment by keszocze** [comment]
Yep, working on it.
Unfortunately, I already added other stuff I wanted to use:
* be able to use the options to `enumerate_linear_transformations` from command line (most likely, how I did it is quite complicated)
* change some `auto`'s to concrete types to get rid of compiler warnings
